### ISSUE TITLE
Java library

### ISSUE THREAD

**Issue by joesondow** [bluesky-social/atproto-ecosystem#36]
This is a request for a Java library for authenticating and posting on Bluesky.

For my use case, I'm moving my popular twitter bots @PicardTips @RikerGoogling @EmojiAquarium @EmojiMeadow @TinyPettingZoo etc. from Twitter to other platforms like Mastodon, Tumblr, and hopefully Bluesky. My work is all in Java, so the lack of a Java library for Bluesky puts Bluesky lower on my priority list to implement for.

**Comment by TomCools** [comment]
Hi @joesondow. I'm currently working on some tools for Java.
It's not there yet, but getting close to something workable.

Could you let me know what kinds of features you need? 
Is it just Posting? Or also reading and such? Since I'm building it up now, I could focus on the features you need first.

**Comment by joesondow** [comment]
Thanks Tom. Over the weekend I cobbled together some janky HTTP and JSON code to work around the lack of a Java library for the short term, just to get my bots up and running. But for other developers making bots in Java, I would expect authenticating and posting would be concern number one, yes.

**Comment by lamrongol** [comment]
https://github.com/uakihir0/bsky4j may be what you need.

**Comment by smileostrich** [comment]
[This Project](https://github.com/smileostrich/bluesky-api-client) could be helpful!

### Related PR
https://github.com/bluesky-social/atproto-ecosystem/pull/49

**Comment by TomCools** [comment]
I decided I didn't just want to create a Bluesky client, but also an AT-Protocol parser and code generator. 

Initial work is here, still needs a lot more work, but I got a code-generator for Lexicon files and a Maven plugin + and example client to show how it could work together. https://github.com/TomCools/AT-Protocol-Java

**Comment by emilyliu7321** [comment]
@TomCools i'll email you an invite code to the email address in your github profile :)

**Comment by emilyliu7321** [comment]
we'll be deprecating this repo shortly and using https://atproto.com/community/projects as the public-facing page for community projects. you can also make PRs to that site here: https://github.com/bluesky-social/atproto-website

i'm going to close this issue in favor of using the matrix channel, in-app discussion, or the community dev discord for now, since this repo is being deprecated, with hopefully a longer-lasting and more easily searchable option/forum to come
